FROM oven/bun:1-alpine

WORKDIR /usr/src/app

# We can pass a build arg when we are building the docker file --> docker run build --build-arg DATABASE_URL=URLHERE -t image_tag .
ARG DATABASE_URL 

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:migrate
RUN DATABASE_URL=${DATABASE_URL} bun run build

COPY . .

EXPOSE 3000

CMD ["bun", "run", "start:web"]